spring:
  application:
    name: task-nest

  datasource:
    url: jdbc:mysql://localhost:3306/task_nest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: task_nest
    password: Aishu$1989

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
